### ISSUE TITLE
Provide migration steps between 1.x and 2.0

### ISSUE THREAD

**Issue by soumak77** [base-apps/angular-base-apps#45]
Update the docs to include steps for how to migrate from 1.x to 2.0:
- [x] How to use angular-front-router (#42)
  - Update [project readme](https://github.com/base-apps/angular-front-router/blob/master/README.md)
- [x] How to use angular-dynamic-routing (#42)
  - Update [project readme](https://github.com/base-apps/angular-dynamic-routing)
- [x] Rename directive prefix from `zf` to `ba`
- [x] Rename services and variables (#44)
